### ISSUE TITLE
Pre-beta roadmap

### ISSUE THREAD

**Issue by akirak** [akirak/emacs-package-checker#39]
The following is a list of todos that must be completed before beta. The current README contains a list of planned features and a progress percentage, but this is a baseline:

- [x] Allow updating emacs-overlay locally
- [ ] Support multi-package repositories
- [ ] Avoid the package-lint workaround
- [ ] Add comprehensive documentation (especially on command line options and environment variables)
- [x] Produce annotations for GitHub Actions
